services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped

  assets-precompile:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: production
        PRECOMPILE_ASSETS: "0"
        # SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        # REDIS_URL: "redis://127.0.0.1:6379/1"
    platform: linux/amd64
    env_file:
      - .env.production
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      REDIS_URL: redis://redis:6379/1
    command: >
      bash -lc '
        set -e
        mkdir -p /app/public/assets
        bin/rails assets:precompile
      '
    volumes:
      - assets:/app/public/assets
      - manifests:/app/public
    depends_on:
      - redis
    restart: "no"

  assets-export:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: production
        PRECOMPILE_ASSETS: "0"
    platform: linux/amd64
    env_file:
      - .env.production
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
      REDIS_URL: redis://redis:6379/1
    command: >
      bash -lc '
        set -e
        mkdir -p /host-public/assets
        rsync -a --delete /app/public/assets/ /host-public/assets/
        rsync -a /app/public/manifest.json /host-public/manifest.json 2>/dev/null || true
        rsync -a /app/public/service-worker.js /host-public/service-worker.js 2>/dev/null || true
        rsync -a /app/public/pwa-icon.png /host-public/pwa-icon.png 2>/dev/null || true
        rsync -a /app/public/icon.png /host-public/icon.png 2>/dev/null || true
        rsync -a /app/public/icon.svg /host-public/icon.svg 2>/dev/null || true
      '
    volumes:
      - ./tmp/local_public:/host-public
      - assets:/app/public/assets
      - manifests:/app/public
    depends_on:
      assets-precompile:
        condition: service_completed_successfully
    restart: "no"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: production
        PRECOMPILE_ASSETS: "0"
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        REDIS_URL: "redis://127.0.0.1:6379/1"
    platform: linux/amd64
    env_file:
      - .env.production
    environment:
      RAILS_ENV: production
      TZ: Asia/Tokyo
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      REDIS_URL: redis://redis:6379/1
    command: bash -lc "rm -f tmp/pids/server.pid && bin/rails s -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_started
      assets-export:
        condition: service_completed_successfully
    volumes:
      - assets:/app/public/assets
      - manifests:/app/public
    restart: unless-stopped

volumes:
  assets:
  manifests:
